import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import * as THREE from 'three';
import {resolveQuality} from '../../共享组件/renderQuality.js';
import {createIntelligenceDirector,intelligenceCycle,intelligenceTiming} from '../src/impact/intelligenceDirector.js';
import {journeyFrame,stageStarts,stageFrames,crystalVertex} from '../src/impact/intelligenceTimeline.js';
import {intelligenceWorld} from '../src/impact/intelligenceWorld.js';
import {intelligenceStages} from '../src/impact/intelligenceContent.js';
const worldSource=readFileSync(new URL('../src/impact/worlds.js',import.meta.url),'utf8');
const {disposeTree}=await import(`data:text/javascript,${encodeURIComponent(worldSource.split('\n').find(line=>line.startsWith('export function disposeTree')))}`);
const near=(a,b,tolerance=1e-6)=>assert.ok(Math.abs(a-b)<tolerance,`${a} != ${b}`);
const advance=(d,seconds,options)=>{for(let i=0;i<Math.round(seconds/.05);i++)d.tick(.05,options);return d.snapshot();};
test('six authored stages cover 108 seconds and repeat deterministically',()=>{
 assert.equal(intelligenceTiming.cycle,108);
 stageStarts.slice(0,6).forEach((t,i)=>assert.equal(journeyFrame(t).stage,i));
 for(let t=0;t<324;t+=.25){const a=journeyFrame(t),b=journeyFrame(t+108);assert.deepEqual(a,b);assert.ok(a.progress>=0&&a.progress<1);}
});
test('all animation channels are finite at boundaries and invalid external time is safe',()=>{
 for(const t of [-108,0,18,34,50,70,90,108,Infinity,NaN])for(const v of Object.values(journeyFrame(t)))assert.ok(Number.isFinite(v));
});
test('the shared clock advances automatically and wraps without resetting accumulated state',()=>{const d=createIntelligenceDirector();advance(d,107.9);const before=d.snapshot();d.tick(.1);near(d.snapshot().time,0);assert.equal(before.stage,5);assert.equal(d.snapshot().stage,0);});
test('manual selection keeps the current frame and approaches the target along the same timeline',()=>{const d=createIntelligenceDirector();advance(d,9);const before=d.snapshot().time;d.select(3);near(d.snapshot().time,before);advance(d,12);near(d.snapshot().time,stageFrames[3]);assert.equal(d.snapshot().mode,'manual');});
test('rapid retargets never reset the visible timestamp',()=>{const d=createIntelligenceDirector();for(const stage of [4,2,5,0,3]){const t=d.snapshot().time;d.select(stage);near(d.snapshot().time,t);advance(d,.3);}advance(d,12);near(d.snapshot().time,stageFrames[3]);});
test('pause freezes playback, and explicitly selecting a stage while paused remains possible',()=>{const d=createIntelligenceDirector();advance(d,20);const t=d.snapshot().time;advance(d,120,{playing:false});near(d.snapshot().time,t);d.select(2);advance(d,12,{playing:false});near(d.snapshot().time,stageFrames[2]);});
for(const gate of [{active:false},{held:true},{suspended:true}])test(`scene gate freezes playback and seeking: ${JSON.stringify(gate)}`,()=>{const d=createIntelligenceDirector();d.select(4);const before=d.snapshot();advance(d,120,gate);assert.deepEqual(d.snapshot(),before);});
test('case reading protects the exact time and returns to the prior playback mode',()=>{const d=createIntelligenceDirector();advance(d,42.3);const t=d.snapshot().time;d.openExample();advance(d,200);near(d.snapshot().time,t);d.closeExample();assert.equal(d.snapshot().mode,'auto');near(d.snapshot().time,t);});
test('manual inactivity resumes after 90 seconds and activity restarts the interval',()=>{const d=createIntelligenceDirector();d.select(3);advance(d,12);advance(d,60);d.activity();advance(d,89);assert.equal(d.snapshot().mode,'manual');advance(d,1.1);assert.equal(d.snapshot().mode,'auto');});
test('reduced motion remains static and allows direct stage selection',()=>{const d=createIntelligenceDirector({reduced:true});advance(d,200);near(d.snapshot().time,16);d.select(5);near(d.snapshot().time,100);d.resume();advance(d,200);near(d.snapshot().time,100);});
test('invalid selections and modified snapshots cannot corrupt the clock',()=>{const d=createIntelligenceDirector();for(const x of [-1,6,NaN,null,'2'])assert.equal(d.select(x),false);const s=d.snapshot();s.weights.fill(9);s.time=22;near(d.snapshot().time,0);assert.deepEqual(d.snapshot().weights,[1,0,0,0,0,0]);});
test('cube geometry actually becomes an elongated diamond with invariant vertex correspondence',()=>{assert.deepEqual(crystalVertex(1.4,1.4,1.4,0),[1.4,1.4,1.4]);const top=crystalVertex(0,1.4,0,1),side=crystalVertex(1.4,0,0,1);near(top[1],2.1);near(side[0],1.5);for(let p=0;p<=1;p+=.05)assert.ok(crystalVertex(1.4,1.4,-1.4,p).every(Number.isFinite));});
function rig(aspect=16/9){
 const originalDocument=globalThis.document,load=THREE.TextureLoader.prototype.load;
 const context=new Proxy({createLinearGradient:()=>({addColorStop(){}}),measureText:text=>({width:text.length*55})},{get:(o,key)=>o[key]??(()=>{}),set:(o,key,v)=>(o[key]=v,true)});
 globalThis.document={createElement:()=>({width:0,height:0,getContext:()=>context})};
 const loaded=[];THREE.TextureLoader.prototype.load=function(path){const data=readFileSync(new URL(`../public${path}`,import.meta.url));assert.equal(data.toString('ascii',12,16),'IHDR');const texture=new THREE.Texture({width:data.readUInt32BE(16),height:data.readUInt32BE(20)});loaded.push(texture);return texture;};
 let world;try{world=intelligenceWorld(resolveQuality(),new THREE.LoadingManager());}finally{THREE.TextureLoader.prototype.load=load;if(originalDocument===undefined)delete globalThis.document;else globalThis.document=originalDocument;}
 const camera=new THREE.PerspectiveCamera(46,aspect,.1,480),position=new THREE.Vector3(),target=new THREE.Vector3();
 const update=t=>{world.update({intelligence:{...intelligenceCycle(t),mode:'auto'},camera:position,target,aspect});camera.position.copy(position);camera.lookAt(target);camera.updateMatrixWorld();world.root.updateMatrixWorld(true);};
 return {world,camera,loaded,update};
}
function visibleState(root){const a=[];root.traverseVisible(o=>{if(o.material)a.push([o.name,...o.matrixWorld.elements,o.material.opacity]);});return a;}
test('only the product asset is loaded; all textures stay reachable for shared disposal',()=>{const {world,loaded}=rig();assert.equal(loaded.length,1);const reachable=new Set();world.root.traverse(o=>{if(o.material?.map)reachable.add(o.material.map);});assert.ok(reachable.has(loaded[0]));const resources=new Map();world.root.traverse(o=>{for(const r of [o.geometry,o.material,o.material?.map])if(r)resources.set(r,0);});resources.forEach((_,r)=>r.addEventListener('dispose',()=>resources.set(r,resources.get(r)+1)));disposeTree(world.root);assert.ok([...resources.values()].every(n=>n===1));});
test('three complete loops reuse every object, geometry, index buffer and product texture',()=>{const {world,update}=rig(),before=[];world.root.traverse(o=>before.push([o,o.geometry,o.material]));for(let t=0;t<324;t+=.5){update(t);let n=0;world.root.traverse(o=>{assert.equal(o,before[n][0]);assert.equal(o.geometry,before[n][1]);assert.equal(o.material,before[n][2]);assert.ok(o.matrixWorld.elements.every(Number.isFinite));n++;});assert.equal(n,before.length);}disposeTree(world.root);});
test('the exact visual loop seam retains one identical review, with no foreign visible objects',()=>{const {world,update}=rig();update(0);const first=visibleState(world.root);update(107.9999);const last=visibleState(world.root);assert.equal(last.length,first.length);first.forEach((record,i)=>record.forEach((v,j)=>typeof v==='number'?near(v,last[i][j],.0001):assert.equal(v,last[i][j])));assert.ok(first.some(v=>v[0]==='record-0'));disposeTree(world.root);});
test('every temporal boundary has continuous visible object transforms and opacity',()=>{const {world,update}=rig();for(const time of [7,17,18,25,27,30,32,33,34,37,39,49,50,54,55,59,66,70,73,76,79,85,90,93,95,100,106]){update(time-.00001);const before=new Map();world.root.traverse(o=>before.set(o,{matrix:[...o.matrixWorld.elements],opacity:o.material?.opacity,visible:o.visible}));update(time+.00001);world.root.traverse(o=>{const b=before.get(o);if(o.visible&&b.visible&&o.material?.opacity>.01){o.matrixWorld.elements.forEach((v,i)=>near(v,b.matrix[i],.003));near(o.material.opacity,b.opacity,.003);}});}disposeTree(world.root);});
for(const [w,h] of [[1366,768],[1920,1080],[3840,2160],[1200,900]])test(`hero contents stay in the right-side safe area at ${w}x${h}`,()=>{const {world,camera,update}=rig(w/h);for(const t of [0,16,31,47,67,77,85,100,107]){update(t);for(const name of ['record-0','persistent-beauty-product','analysis-screen']){const object=world.root.getObjectByName(name);if(!object.visible)continue;const center=new THREE.Vector3();object.getWorldPosition(center);const p=center.project(camera);assert.ok(p.x>=-.22&&p.x<=.94,`${name} at ${t}: ${p.x}`);assert.ok(p.y>-.57&&p.y<.7,`${name} at ${t}: ${p.y}`);}}disposeTree(world.root);});
test('all six stages retain distinct bilingual beauty examples without invented business outcomes',()=>{assert.equal(intelligenceStages.length,6);assert.equal(new Set(intelligenceStages.map(s=>s.id)).size,6);for(const s of intelligenceStages){for(const value of [s.name,s.description,s.example.title,s.example.summary,s.example.outcome,...s.example.steps])assert.ok(value.length===2&&value.every(t=>typeof t==='string'&&t.length));assert.doesNotMatch(JSON.stringify(s.example),/儿童|香水|\d+%/);}});

test('data lattice converges, reconstructs and retires without replacing its instances',()=>{const {world,update}=rig();const lattice=world.root.getObjectByName('data-lattice');assert.equal(lattice.count,98);update(9);const spread=[...lattice.instanceMatrix.array];update(16);const cube=[...lattice.instanceMatrix.array];assert.notDeepEqual(spread,cube);update(28);assert.notDeepEqual([...lattice.instanceMatrix.array],cube);update(33);assert.equal(lattice.visible,false);assert.ok([...lattice.instanceMatrix.array].every(Number.isFinite));disposeTree(world.root);});
test('analysis content is progressively drawn and moves into the same decision card objects',()=>{const {world,update}=rig();const card=world.root.getObjectByName('analysis-card-0'),content=card.children[0];update(39.4);assert.ok(content.userData.reveal.value>0&&content.userData.reveal.value<1);update(47);near(content.userData.reveal.value,1);assert.ok(content.material.opacity>.99);update(67);assert.equal(world.root.getObjectByName('analysis-card-0'),card);assert.equal(content.visible,false);assert.ok(card.material.opacity>.1);disposeTree(world.root);});
test('development inspection parks the common clock without affecting normal playback contracts',()=>{const d=createIntelligenceDirector();d.select(4);d.inspect(28.4);near(d.snapshot().time,28.4);assert.equal(d.snapshot().seeking,false);advance(d,8,{playing:false});near(d.snapshot().time,28.4);d.resume();advance(d,1);near(d.snapshot().time,29.4);d.inspect(NaN);near(d.snapshot().time,29.4);});
test('the product belongs to the recommendation before cards begin orbiting',()=>{const {world,update}=rig();for(const t of [55,58,61,66,69]){update(t);const product=world.root.getObjectByName('persistent-beauty-product'),card=world.root.getObjectByName('analysis-card-4');near(product.position.x,card.position.x);near(product.position.y,card.position.y-.08);near(product.position.z,card.position.z+.08);}disposeTree(world.root);});

test('opening types from G into the review and reverses to the identical letter at the seam',()=>{const {world,update}=rig(),text=world.root.getObjectByName('record-0');update(0);assert.equal(text.userData.typedCount,1);const cut=text.userData.typing.cut.value;update(1);assert.ok(text.userData.typedCount>1&&text.userData.typedCount<14);update(3);assert.equal(text.userData.typedCount,14);update(107.9999);assert.equal(text.userData.typedCount,1);near(text.userData.typing.cut.value,cut);disposeTree(world.root);});
test('robot blinks, floats and turns toward the spatial screen',()=>{const {world,update}=rig(),eye=world.root.getObjectByName('robot-eyes'),bot=world.root.getObjectByName('data-to-assistant');update(31.94);assert.ok(eye.scale.y<.2);update(33);assert.ok(eye.scale.y>.99);const first=bot.position.y;update(43);assert.notEqual(bot.position.y,first);assert.ok(bot.rotation.y<-.2);assert.ok(eye.position.x<0);assert.ok(world.root.getObjectByName('analysis-screen').rotation.y>.4);update(55);near(world.root.getObjectByName('analysis-screen').rotation.y,0);disposeTree(world.root);});
test('scan volume originates at the moving eye and meets the inclined screen in 3D',()=>{const {world,update}=rig(),beam=world.root.getObjectByName('right-to-left-projection');update(42);const root=world.root.getObjectByName('continuous-value-journey'),core=world.root.getObjectByName('robot-projector'),eye=root.worldToLocal(core.getWorldPosition(new THREE.Vector3()));beam.userData.source.forEach((v,i)=>near(v,eye.getComponent(i)));assert.ok(beam.userData.target[0]<beam.userData.source[0]);const zs=Array.from(beam.geometry.attributes.position.array).filter((_,i)=>i%3===2);assert.ok(Math.max(...zs)-Math.min(...zs)>.5);const before=beam.userData.target[1];update(44);assert.notEqual(beam.userData.target[1],before);disposeTree(world.root);});
