import { lazy, Suspense, useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, ArrowUpRight, CornersOut, SquaresFour, Play, Pause } from '@phosphor-icons/react';
const WorldScene = lazy(() => import('./components/WorldScene').then(m => ({ default:m.WorldScene })));
const ConnectedScene = lazy(() => import('./components/ConnectedScene').then(m => ({ default:m.ConnectedScene })));
import { BrandCarousel, SampleWall } from './components/Galleries';
import { Modal, SampleViewer, Switcher } from './components/Dialogs';
import { fallbackContent, variants } from './content';
import { useIdle, useRoute } from './hooks';
import { CompanyStory } from './components/CompanyStory';
import { CatalogBrowser } from './components/CatalogBrowser';
import { FactoryDetail } from './components/FactoryDetail';

export function App() {
  const [route, go] = useRoute();
  const [lang, setLang] = useState(() => localStorage.getItem('showroom-language') || 'zh');
  const [content, setContent] = useState(fallbackContent), [switcher, setSwitcher] = useState(false), [selectedLocation, setSelectedLocation] = useState('china');
  const [activeBrand, setActiveBrand] = useState(0), [enteredBrand, setEnteredBrand] = useState(null), [filter, setFilter] = useState('all');
  const [sample, setSample] = useState(null), [locationOpen, setLocationOpen] = useState(false), [videoPlaying, setVideoPlaying] = useState(false), [manualTour, setManualTour] = useState(false), [notice, setNotice] = useState('');
  const [focusKey, setFocusKey] = useState(0);
  const [capability,setCapability]=useState('overview'),[capabilityFocus,setCapabilityFocus]=useState(null);
  const enterLocation=()=>{setCapability('overview');setCapabilityFocus(null);setLocationOpen(true);};
  const changeCapability=id=>{setCapability(id);setCapabilityFocus(null);setVideoPlaying(false);};
  const [chapter, setChapter] = useState(0), [official, setOfficial] = useState(null), [catalog, setCatalog] = useState(null), [archive, setArchive] = useState(null);
  const archiveMemory = useRef({brands:{}, categories:{}});
  const [closingLayer,setClosingLayer]=useState(false), closeTimer=useRef(null);
  const closeOverlay=(setter,value=false)=>{if(closeTimer.current)clearTimeout(closeTimer.current);setClosingLayer(true);closeTimer.current=setTimeout(()=>{setter(value);setClosingLayer(false);closeTimer.current=null;},220);};
  useEffect(()=>()=>clearTimeout(closeTimer.current),[]);
  const selectLocation = id => { setSelectedLocation(id); setFocusKey(v => v + 1); };
  const wallPosition = useRef({ x: 0, y: 0 }), tourStep = useRef(0);
  const l = lang === 'zh' ? 0 : 1, t = (zh, en) => l === 0 ? zh : en;
  const variant = variants.find(v => v.id === route.variant), home = route.page === 'home';
  const loc = content.locations.find(v => v.id === selectedLocation) || content.locations[0];
  const brand = content.brands.find(b => b.id === enteredBrand);
  const wallItems = brand ? content.samples.filter(s => s.brand === brand.id) : content.samples.filter(s => filter === 'all' || s.category === filter);
  const viewerItems = locationOpen ? content.samples : (route.variant === 'studio' || route.page === 'brands') ? wallItems : content.samples.filter(s => filter === 'all' || s.category === filter);
  useEffect(() => { Promise.all([['showroom',setContent],['official-content',setOfficial],['catalog',setCatalog]].map(async ([file,save])=>{const r=await fetch(`/data/${file}.json`);if(!r.ok)throw Error(file);save(await r.json());})).catch(()=>setNotice(t('部分内容未能加载，请重新打开页面。','Some content could not load. Please reload the page.'))); }, []);
  useEffect(() => { localStorage.setItem('showroom-language', lang); document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en'; }, [lang]);
  useEffect(() => { setSample(null); setLocationOpen(false); setEnteredBrand(null); setVideoPlaying(false); setArchive(null); }, [route.variant, route.page]);
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(''), 3500); return () => clearTimeout(timer); }, [notice]);
  const nextTour = () => { if(variant.id==='atlas'){const states=[['home',0],['home',1],['home',2],['home',3],['locations','china'],['locations','cambodia'],['locations','usa'],['brands',0],['brands',1],['brands',4],['products',0]];const [page,value]=states[tourStep.current++%states.length];if(page==='home')setChapter(value);if(page==='locations')selectLocation(value);if(page==='brands')setActiveBrand(value%content.brands.length);go('atlas',page);}else{const page=tourStep.current++%2===0?'home':variant.page;go(variant.id,page);setActiveBrand(i=>(i+1)%content.brands.length);} };
  const [idle, wake] = useIdle({ seconds: content.settings.idleSeconds, slideSeconds: content.settings.slideSeconds, paused: manualTour || videoPlaying || !!sample || switcher || locationOpen || !!archive, onSlide: nextTour });
  useEffect(() => { if (!manualTour) return; nextTour(); const timer = setInterval(nextTour, content.settings.slideSeconds * 1000); const stop = e => { if (!e.target.closest?.('.tour-button')) setManualTour(false); }; window.addEventListener('pointerdown', stop); window.addEventListener('keydown', stop); return () => { clearInterval(timer); window.removeEventListener('pointerdown', stop); window.removeEventListener('keydown', stop); }; }, [manualTour]);
  async function fullscreen() { try { if (document.fullscreenElement) await document.exitFullscreen(); else await document.documentElement.requestFullscreen(); } catch { setNotice(t('当前浏览器未开放全屏，可使用系统全屏。', 'Fullscreen is unavailable here. Use your browser fullscreen control.')); } }
  const openBrand = b => { setEnteredBrand(b.id); wallPosition.current = { x: 0, y: 0 }; };
  const activeHomeAction = () => go(variant.id, variant.page);
  return <main className={`showroom theme-${variant.theme} variant-${variant.id} ${home ? 'is-home' : 'is-capability'} ${locationOpen?'has-location-detail':''} ${home&&chapter>0?'has-story':''} ${closingLayer?'closing-layer':''}`}>
    <header className="topbar"><button className="brand-lockup" aria-label={t('返回公司首页', 'Company home')} onClick={() => go(variant.id, 'home')}><img className="corporate-logo" src={variant.theme === 'dark' ? '/media/brand/logo-w.png' : '/media/brand/logo.svg'} alt="PARAMONT GROUP" /><span>{t('数字展厅', 'DIGITAL SHOWROOM')}</span></button><div className="top-actions"><div className="language-switch" aria-label={t('语言', 'Language')}><button className={lang === 'zh' ? 'active' : ''} onClick={() => setLang('zh')} aria-pressed={lang === 'zh'}>中文</button><span>/</span><button className={lang === 'en' ? 'active' : ''} onClick={() => setLang('en')} aria-pressed={lang === 'en'}>EN</button></div><button className="icon-button fullscreen" onClick={fullscreen} aria-label={t('切换全屏', 'Toggle fullscreen')}><CornersOut size={25} /></button></div></header>
    {variant.id === 'atlas' && <Suspense fallback={(home||route.page==='locations')?<div className="world-loading">{t('正在进入公司世界','Entering our world')}</div>:null}><ConnectedScene page={route.page} chapter={chapter} paused={!(home||route.page==='locations')||switcher||!!sample||!!archive||videoPlaying} locations={content.locations} selected={selectedLocation} focusKey={focusKey} onSelect={id=>{if(id===selectedLocation)enterLocation();else selectLocation(id);}} onEnter={page => go('atlas',page)} lang={lang} capability={locationOpen?capability:null} capabilityFocus={capabilityFocus} onCapability={changeCapability} onCapabilityFocus={setCapabilityFocus} /></Suspense>}
    {variant.id === 'atlas' && (home || route.page === 'locations') && <>
      {home ? <CompanyStory chapter={chapter} onChapter={setChapter} official={official} lang={lang} onEnter={page=>go('atlas',page)}/> : <section className="atlas-copy connected-location-copy" key={selectedLocation}><p className="eyebrow">{t('全球布局与能力','PLACES & CAPABILITIES')}</p><h1>{loc.name[l]}</h1><button className="primary-link" onClick={()=>enterLocation()}>{t('探索当地能力','Explore this location')}<ArrowRight size={28}/></button><p className="supporting-copy">{t('走进空间、工艺、质量与交付。','Explore the place, process, quality and delivery.')}</p></section>}
      {!home && <div className="location-controls"><div className="segmented-control">{content.locations.map(c=><button key={c.id} aria-pressed={c.id===selectedLocation} className={c.id===selectedLocation?'active':''} onClick={()=>{if(c.id===selectedLocation)enterLocation();else selectLocation(c.id);}}>{c.name[l]}</button>)}</div></div>}
    </>}
    {variant.id === 'studio' && home && <><Suspense fallback={null}><WorldScene mode="mountain" variant="studio" lang={lang} /></Suspense><section className="studio-home-copy"><p className="eyebrow">PARAMONT / CREATIVE MATTER</p><h1>{t('灵感，有了形状。', 'Ideas take shape.')}</h1><p>{t('用设计连接品牌，用产品传递创意。', 'Design connects brands. Products bring ideas to life.')}</p><button className="pill-button" onClick={activeHomeAction}>{t('进入品牌世界', 'Enter our brand world')}<ArrowUpRight size={25} /></button></section></>}
    {((variant.id === 'studio' && !home) || (variant.id === 'atlas' && route.page === 'brands')) && <>
      {!brand ? <><section className="gallery-heading"><p className="eyebrow">WEVEEL / BRAND COLLECTION</p><h1>{t('每个品牌，一个创意世界。', 'A world behind every brand.')}</h1></section>{catalog&&<button className="archive-entry" onClick={()=>setArchive('brands')}><SquaresFour size={22}/>{t('全部品牌档案','All brand records')}<span>{catalog.brands.length}</span><ArrowUpRight size={20}/></button>}<BrandCarousel brands={content.brands} active={activeBrand} onActive={setActiveBrand} onEnter={openBrand} lang={lang} /><p className="concept-note">{t('品牌信息来自官网 · 配图为视觉概念', 'Brand information from the official site · Concept artwork')}</p></> : <div className="brand-room"><button className="text-button brand-room-back" onClick={() => { setEnteredBrand(null); setSample(null); }}><ArrowLeft size={22} />{t('返回品牌画廊', 'Back to brand gallery')}</button><aside className="brand-room-story"><p className="eyebrow">WEVEEL / BRAND IN FOCUS</p><div className="brand-room-logo"><img src={`/media/brand/${brand.logo}`} alt={brand.name}/></div><h1>{brand.descriptor[l]}</h1><p>{brand.description[l]}</p><div className="brand-room-caption"><span>{String(wallItems.length).padStart(2,'0')}</span><div>{t('概念样品','Concept studies')}<small>{t('用于探索视觉与交互，非实际产品。','Visual and interaction studies, not actual products.')}</small></div></div>{catalog&&<button className="text-button" onClick={()=>setArchive('brands')}>{t('打开全部品牌档案','Open brand archive')}<ArrowRight size={22}/></button>}</aside><SampleWall samples={wallItems} lang={lang} onSelect={setSample} savedPosition={wallPosition} /></div>}
    </>}
    {variant.id === 'gallery' && home && <><section className="gallery-home-title"><p className="eyebrow">PARAMONT / INFINITE EDITIONS</p><h1>{t('让日常，充满可能。', 'Everyday, reimagined.')}</h1><p>{t('在品类之间，发现下一份灵感。', 'Find your next idea across our creative categories.')}</p></section><BrandCarousel brands={content.brands} active={activeBrand} onActive={setActiveBrand} onEnter={() => go('gallery', 'categories')} lang={lang} home /><button className="gallery-home-cta pill-button" onClick={activeHomeAction}>{t('探索品类与样品', 'Explore categories')}<ArrowRight size={24} /></button><p className="concept-note">{t('图片为本轮视觉概念', 'Artwork created for this visual study')}</p></>}
    {((variant.id === 'gallery' && !home) || (variant.id === 'atlas' && route.page === 'products')) && <><section className="wall-heading categories-heading"><div><p className="eyebrow">PARAMONT / MATERIAL LIBRARY</p><h1>{t('灵感，触手可及。', 'Ideas within reach.')}</h1></div><span className="concept-tag">{t('概念样品 · 非实际产品', 'CONCEPT SAMPLES · NOT PRODUCT LISTINGS')}</span></section>{catalog&&<button className="archive-entry category-archive-entry" onClick={()=>setArchive('categories')}><SquaresFour size={22}/>{t('品类总览','Category index')}<span>{catalog.categories.length}</span><ArrowUpRight size={20}/></button>}<SampleWall samples={wallItems} lang={lang} onSelect={setSample} savedPosition={wallPosition} /><div className="category-controls segmented-control">{content.categories.map(c => <button key={c.id} className={c.id === filter ? 'active' : ''} aria-pressed={c.id === filter} onClick={() => setFilter(c.id)}>{c.name[l]}</button>)}</div></>}
    <footer className="bottom-bar"><button className="switch-variant" aria-label={t('切换方案','Choose a direction')} onClick={() => setSwitcher(true)}><SquaresFour size={24} /><span>{t('切换方案', 'Directions')}</span></button><nav aria-label={t('章节导航', 'Chapter navigation')}>{variant.id === 'atlas' ? [['home','公司世界','Company world'],['locations','全球布局','Global presence'],['brands','品牌世界','Brand worlds'],['products','产品探索','Product discovery']].map(([page,zh,en])=><button key={page} className={route.page===page?'active':''} aria-current={route.page===page?'page':undefined} onClick={()=>{if(page==='locations')setLocationOpen(false);go('atlas',page);}}>{t(zh,en)}</button>) : <><button className={home ? 'active' : ''} onClick={() => go(variant.id, 'home')} aria-current={home ? 'page' : undefined}>{t('公司介绍', 'Company')}</button><button className={!home ? 'active' : ''} onClick={activeHomeAction} aria-current={!home ? 'page' : undefined}>{variant.pageLabel[l]}</button></>}</nav><button className="tour-button" onClick={() => { wake(); setManualTour(v => !v); }} aria-label={t('开始或停止自动展示', 'Start or stop presentation')}>{(manualTour || idle) ? <Pause size={18} /> : <Play size={18} />}<span>{t('自动展示', 'Presentation')}</span></button></footer>
    {(idle || manualTour) && <div className="tour-badge">{t('自动展示中', 'Presentation')}</div>}{notice && <div className="toast" role="status">{notice}</div>}
    {switcher && <Switcher current={variant.id} lang={lang} sampleImages={['a3-paper-mountains.png', 'a1-markers.png', 'b1-wooden-arches.png']} onClose={() => setSwitcher(false)} onChoose={id => { go(id); setSwitcher(false); }} />}
    {sample && <SampleViewer samples={viewerItems} selected={sample} onChange={setSample} onClose={() => closeOverlay(setSample,null)} lang={lang} onVideoPlaying={setVideoPlaying} />}
    {locationOpen && <FactoryDetail location={loc} lang={lang} tab={capability} onTab={changeCapability} focus={capabilityFocus} onFocus={setCapabilityFocus} onClose={()=>{setVideoPlaying(false);setLocationOpen(false);}} onVideoPlaying={setVideoPlaying} onSample={id=>setSample(id)}/>}
    {archive&&catalog&&<CatalogBrowser key={archive} type={archive} catalog={catalog} featured={content.brands} lang={lang} remembered={archiveMemory.current[archive]} onRemember={value=>archiveMemory.current[archive]=value} onClose={()=>closeOverlay(setArchive,null)} onBrand={b=>{setArchive(null);openBrand(b);}}/>}
  </main>;
}
