import * as T from 'three';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {createProduct,disposeProduct,applyPalette} from './models.js';
document.body.innerHTML='<div style="position:fixed;z-index:9;padding:16px;color:white;background:#082e54" id="progress">Preparing original concept renders…</div>';
const renderer=new T.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setSize(1000,800);renderer.setPixelRatio(1);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;document.body.append(renderer.domElement);
const scene=new T.Scene();scene.background=new T.Color('#0b2239');const pm=new T.PMREMGenerator(renderer),room=new RoomEnvironment();scene.environment=pm.fromScene(room,.04).texture;scene.environmentIntensity=.75;room.dispose();pm.dispose();scene.add(new T.HemisphereLight('#e4efff','#243245',.65));const key=new T.DirectionalLight('#ffe4ce',3.2);key.position.set(-3,5,6);scene.add(key);const rim=new T.DirectionalLight('#aad7ff',3);rim.position.set(4,3,-4);scene.add(rim);const camera=new T.PerspectiveCamera(34,1.25,.1,50);camera.position.set(0,1,7.5);camera.lookAt(0,0,0);
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const save=(filename,body)=>fetch('/__capture?file='+filename,{method:'POST',body}).then(r=>{if(!r.ok)throw Error(filename);});
async function run(){const variants=new URLSearchParams(location.search).has('variants');const source=await(await fetch(variants?'/shared/product-skus.json':'/shared/concepts.json')).json();const items=variants?source.items.filter(s=>Object.keys(s.palette).length):source.items;for(const item of items){document.getElementById('progress').textContent='Rendering '+item.id;const model=createProduct(item.productId||item.id);if(item.palette)applyPalette(model,item.palette);scene.add(model);for(let i=0;i<3;i++){model.rotation.y=[-.28,1.22,.5][i];camera.position.set(i===2?.4:0,i===2?1.35:1,i===2?5.0:7.5);camera.lookAt(0,i===2?.3:0,0);renderer.render(scene,camera);const blob=await new Promise(r=>renderer.domElement.toBlob(r,'image/png'));await save(item.id+'-'+i+'.png',blob);}
 camera.position.set(0,1,7.5);camera.lookAt(0,0,0);const stream=renderer.domElement.captureStream(24);const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm';const recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:1500000});const chunks=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};const finished=new Promise(resolve=>recorder.onstop=resolve);recorder.start();let start=performance.now();while(performance.now()-start<3500){model.rotation.y=(performance.now()-start)/3500*Math.PI*2-.28;renderer.render(scene,camera);await wait(40);}recorder.stop();await finished;stream.getTracks().forEach(t=>t.stop());await save(item.id+'.webm',new Blob(chunks,{type:'video/webm'}));scene.remove(model);disposeProduct(model);}
 document.getElementById('progress').textContent='COMPLETE: '+items.length+' concepts rendered with three angles and a film each';document.body.dataset.complete='true';}
run().catch(e=>{console.error(e);document.getElementById('progress').textContent='ERROR: '+e.message;});
