import {useEffect,useLayoutEffect,useRef} from 'react';
import {asset,brandCopy} from './content.js';
import {ProductCollection,ProductRail} from './ProductCollection.jsx';
import {productResults,skusFor} from './product-data.js';
export const initialLibrary={tab:'brands',scope:'official',brandId:'scentos',record:null,categoryId:'15',subcategoryId:null,categorySearch:null,query:'',layout:'list',productCategoryId:'all',productBrandId:'all'};
const names={brands:['品牌','Brands'],categories:['品类','Categories'],products:['产品','Products']};
const archiveMatches={scentos:'Scentos','sugar-rush':'Sugar Rush','yay-hooray':'Yay Hooray!'};
export function Library({sharedShell=false,data,lang,state,memory,onChange,onClose,onProduct,onDomain}){
 const l=lang==='zh'?0:1,t=(zh,en)=>l===0?zh:en,dialog=useRef(),body=useRef(),categoryRail=useRef(),categoryBody=useRef(),scroll=memory,priorFocus=useRef();
 const {tab,scope,brandId,record,categoryId,subcategoryId,query,layout}=state;
 const key=[tab,scope,record?.id||'',categoryId,subcategoryId,query,layout].join('/');
 const change=patch=>onChange({...state,...patch});
 useEffect(()=>{priorFocus.current=document.activeElement;dialog.current.focus();return()=>priorFocus.current?.focus?.();},[]);
 useLayoutEffect(()=>{if(body.current)body.current.scrollTop=scroll.current[key]||0;if(categoryRail.current){categoryRail.current.scrollTop=scroll.current.categoryRail||0;categoryRail.current.querySelector('.active')?.scrollIntoView({block:'nearest'});}if(categoryBody.current)categoryBody.current.scrollTop=scroll.current['category/'+categoryId+'/'+subcategoryId]||0;},[key]);
 const search=r=>[r.name,r.id,...(r.label||[])].join(' ').toLowerCase().includes(query.trim().toLowerCase());
 const matchingBrands=data.brands.filter(b=>[b.name,b.zh_descriptor,...Object.values(brandCopy[b.id]||{}).flat()].join(' ').toLowerCase().includes(query.toLowerCase()));
 const brand=matchingBrands.find(b=>b.id===brandId)||matchingBrands[0];
 const category=data.catalog.categories.find(c=>c.id===categoryId)||data.catalog.categories[0];
 const subcategory=data.catalog.subcategories.find(c=>c.id===subcategoryId);
 const domain=data.domains.find(d=>d.categoryId===category.id);
 const subs=data.catalog.subcategories.filter(c=>c.parent===category.id);
 const matches=data.items.filter(p=>subcategory?p.subcategoryId===subcategory.id:subs.some(s=>s.id===p.subcategoryId));
 function back(){if(tab==='brands'&&record)change({record:null});else if(tab==='categories'&&state.categorySearch)change({query:state.categorySearch,categorySearch:null,subcategoryId:null});else if(tab==='categories'&&subcategoryId)change({subcategoryId:null});else onClose();}
 function trap(e){if(e.key==='Escape'){e.preventDefault();e.stopPropagation();back();}if(sharedShell||e.key!=='Tab')return;const nodes=[...dialog.current.querySelectorAll('button:not([disabled]),input,select,a[href]')].filter(n=>n.offsetParent!==null),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===dialog.current)){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}
 function renderBrand(b){return <div className="brand-focus" key={b.id}>
  <div className={`brand-art brand-art-${b.id}`}><div className="brand-orbit"/><div className="brand-emblem"><img src={asset('shared/brand/'+b.logo.split('/').at(-1))} alt={b.name}/></div><span className="art-caption">{t('品牌识别','BRAND IDENTITY')}</span></div>
  <article className="brand-story"><div className="eyebrow">{t('走进品牌','INSIDE THE BRAND')}</div><h2>{b.name}</h2><h3>{brandCopy[b.id]?.descriptor[l]||(l===0?b.zh_descriptor:b.name)}</h3><div className="brand-intro-label">{t('品牌介绍','The introduction')}</div><p>{brandCopy[b.id]?.description[l]}</p><div className="brand-pillars">{(brandCopy[b.id]?.pillars||[]).map((label,i)=><div key={i}><small>0{i+1}</small><span>{label[l]}</span></div>)}</div>{data.items.some(p=>p.brandId===b.id)&&<button className="primary" onClick={()=>change({tab:'products',productBrandId:b.id,productCategoryId:'all',query:''})}>{t('探索品牌产品','Explore brand products')} →</button>}{archiveMatches[b.id]&&<button className="text-link" onClick={()=>change({scope:'archive',query:archiveMatches[b.id],record:null})}>{t('查看品牌档案','View brand record')} →</button>}</article>
 </div>;}
 return <div className="overlay library-overlay" onPointerDown={e=>{if(e.target===e.currentTarget)onClose();}}><section ref={dialog} className="dialog explorer-library" role={sharedShell?'region':'dialog'} aria-modal={sharedShell?undefined:true} aria-label={t('品牌、品类与产品探索','Brand, category and product explorer')} tabIndex={-1} onKeyDown={trap}>
  <header className="library-header"><div className="eyebrow">PARAMONT / {t('探索档案','EXPLORER')}</div>{sharedShell?<h1 className="library-section-title">{names[tab][l]}</h1>:<nav aria-label={t('探索类型','Explore by')}>{Object.entries(names).map(([id,label])=><button key={id} aria-current={tab===id?'page':undefined} className={tab===id?'active':''} onClick={()=>change({tab:id,query:'',record:null,subcategoryId:null,categorySearch:null})}>{label[l]}</button>)}</nav>}<button className="library-close" onClick={onClose}>{t('返回场景','Back to scene')} <span>×</span></button></header>
  <div className="library-toolbar">
   {tab==='brands'&&<div className="segmented"><button className={scope==='official'?'active':''} onClick={()=>change({scope:'official',query:'',record:null})}>{t('精选品牌','Featured brands')} <small>{String(data.brands.length).padStart(2,'0')}</small></button><button className={scope==='archive'?'active':''} onClick={()=>change({scope:'archive',query:'',record:null})}>{t('品牌档案','Brand archive')} <small>{data.catalog.brands.length}</small></button></div>}
   {tab==='categories'&&<p>{data.catalog.categories.length} {t('大类','categories')} <span>/</span> {data.catalog.subcategories.length} {t('细分类','subcategories')}</p>}
   {tab==='products'&&<p>{t('产品目录','Product collection')} <span>/</span> {t('按名称、品类或款式查找','Find a product or style')}</p>}
   <input type="search" aria-label={t('搜索探索内容','Search explorer')} value={query} placeholder={t(tab==='categories'?'搜索全部大类与细分类':tab==='products'?'搜索产品名称、品类或款式编号':'搜索品牌名称',tab==='categories'?'Search all categories and subcategories':tab==='products'?'Search product, category or style code':'Search brand names')} onChange={e=>change({query:e.target.value,record:null})}/>
   {tab==='brands'&&scope==='archive'&&<button onClick={()=>change({layout:layout==='list'?'gallery':'list'})}>{layout==='list'?t('画廊视图','Gallery view'):t('列表视图','List view')}</button>}
  </div>
  <div className="library-body" ref={body} onScroll={e=>{scroll.current[key]=e.currentTarget.scrollTop;}}>
  {tab==='brands'&&(scope==='official'?<div className="brand-exhibit"><div className="brand-rail" aria-label={t('选择品牌','Choose brand')}>{matchingBrands.map((b,i)=><button className={b.id===brand.id?'active':''} aria-pressed={b.id===brand.id} key={b.id} onClick={()=>change({brandId:b.id})}><span>0{data.brands.indexOf(b)+1}</span><img src={asset('shared/brand/'+b.logo.split('/').at(-1))} alt={b.name}/></button>)}{!data.brands.some(b=>[b.name,b.zh_descriptor,...Object.values(brandCopy[b.id]||{}).flat()].join(' ').toLowerCase().includes(query.toLowerCase()))&&<p className="empty">{t('没有匹配的品牌','No matching brands')}</p>}</div>{brand?renderBrand(brand):<div className="empty">{t('换一个名称继续探索，或查看完整品牌档案。','Try another name, or browse the full brand archive.')}</div>}</div>:record?<article className="archive-record"><button className="text-link" onClick={()=>change({record:null})}>← {t('返回搜索结果','Back to results')}</button><div className="eyebrow">{t('品牌档案','BRAND RECORD')} / {record.id}</div><h2>{record.name}</h2><div className="record-note">{t('已收录品牌名称，尚未关联产品系列。档案收录不代表品牌归属或授权。','Brand name on record; no product range linked. Inclusion does not establish ownership or licensing.')}</div>{data.brands.filter(b=>archiveMatches[b.id]===record.name).map(b=><button className="primary" key={b.id} onClick={()=>change({scope:'official',brandId:b.id,record:null,query:''})}>{t('查看品牌展示','Explore this brand')} →</button>)}</article>:<><div className="archive-context">{t('品牌档案 · 收录不代表品牌归属或授权','Brand archive · Inclusion does not establish ownership or licensing')}</div><div className={'archive-rows '+layout}>{data.catalog.brands.filter(search).map((b,i)=><button key={b.id} className="archive-row" onClick={()=>change({record:b})}><small>{String(i+1).padStart(2,'0')}</small><span>{b.name}</span></button>)}</div>{!data.catalog.brands.some(search)&&<div className="empty">{t('没有匹配的品牌记录','No matching brand records')}</div>}</>)}
  {tab==='categories'&&(query?<div className="category-search-results">{[...data.catalog.categories,...data.catalog.subcategories].filter(search).map(c=><button className="archive-row" key={(c.parent||'main')+c.id} onClick={()=>change({categoryId:c.parent||c.id,subcategoryId:c.parent?c.id:null,query:'',categorySearch:query})}><small>{c.id}</small><span>{c.label?.[l]||c.name}</span><em>{c.parent?(data.catalog.categories.find(p=>p.id===c.parent)?.label?.[l]||c.parent):t('大类','Category')}</em></button>)}{![...data.catalog.categories,...data.catalog.subcategories].some(search)&&<p className="empty">{t('没有匹配的品类','No matching categories')}</p>}</div>:<div className="category-exhibit"><aside className="category-rail" ref={categoryRail} onScroll={e=>{scroll.current.categoryRail=e.currentTarget.scrollTop;}}>{data.catalog.categories.map(c=><button className={category.id===c.id?'active':''} aria-pressed={category.id===c.id} key={c.id} onClick={()=>change({categoryId:c.id,subcategoryId:null,categorySearch:null})}><small>{c.id}</small><span>{c.label?.[l]||c.name}</span></button>)}</aside><section className="category-focus" ref={categoryBody} onScroll={e=>{scroll.current['category/'+categoryId+'/'+subcategoryId]=e.currentTarget.scrollTop;}}><div className="eyebrow">{t('品类目录','CATEGORY')} / {category.id}{subcategory&&' / '+subcategory.id}</div>{state.categorySearch?<button className="text-link" onClick={()=>change({query:state.categorySearch,categorySearch:null,subcategoryId:null})}>← {t('返回搜索结果','Back to search results')}</button>:subcategory&&<button className="text-link" onClick={()=>change({subcategoryId:null})}>← {category.label?.[l]||category.name}</button>}<h2>{(subcategory||category).label?.[l]||(subcategory||category).name}</h2><p className="category-source">{subcategory?t('细分类','Subcategory'):subs.length+' '+t('个细分类','subcategories')}</p>{domain&&!subcategory&&<button className="text-link" onClick={()=>onDomain(domain.id)}>{t('进入此领域的产品场景','Enter this product world')} →</button>}
   {matches.length>0&&<div className="category-products"><div className="section-heading"><span>{t('此分类的产品','Products in this category')}</span><small>{matches.length} {t('产品','products')} / {matches.reduce((n,p)=>n+skusFor(data,p.id).length,0)} {t('款式','styles')}</small></div><ProductRail results={productResults(data,{categoryId:category.id,subcategoryId:subcategory?.id})} data={data} lang={lang} onProduct={onProduct} memory={memory} memoryKey={'category-rail/'+categoryId+'/'+subcategoryId}/></div>}

   {!subcategory?<details className="subcategory-disclosure" open={matches.length===0?true:undefined}><summary>{t('细分类','Subcategories')} <span>{subs.length}</span></summary><div className="subcategory-list">{subs.map(s=><button key={s.id} onClick={()=>change({subcategoryId:s.id})}><small>{s.id}</small><span>{s.label?.[l]||s.name}</span></button>)}</div></details>:<div className="category-detail-note"><h3>{t('品类位置','In the catalog')}</h3><p>{category.label?.[l]||category.name} → {subcategory.label?.[l]||subcategory.name}</p><p>{t(matches.length?'概念样品 · 非真实产品 · 未绑定品牌':'暂无关联产品。',matches.length?'Concept studies · Not actual products · No brand assigned':'No linked products yet.')}</p></div>}
  </section></div>)}
  {tab==='products'&&<ProductCollection data={data} lang={lang} state={state} onChange={onChange} onProduct={onProduct} memory={memory}/>}

  </div>
 </section></div>;
}
