// A review is one source in a wider business feedback loop. These are illustrative
// record structures and review questions, never asserted operating results.
export const feedbackSources = [
 {id:'customer',report:0,text:['很棒的产品。','Great product.'],title:['客户使用反馈','CUSTOMER FEEDBACK'],
  source:['使用体验 / 演示摘录','USE EXPERIENCE / DEMO']},
 {id:'sales',report:3,text:['销量，要和预测一起看。','Compare sales with the forecast.'],title:['销售与预测复盘','SALES / FORECAST REVIEW'],
  source:['销售记录 / 同商品、同期间','SALES / SAME PRODUCT AND PERIOD'],
  plan:['按商品与月份形成需求预测。','Forecast demand by product and month.'],
  actual:['对照实销数量与销售金额。','Compare actual units and sales revenue.'],
  action:['记录偏差，再更新下一轮需求判断。','Record the gap; refine the next demand forecast.']},
 {id:'inventory',report:3,text:['卖得少，也可能是缺货。','Low sales can also mean no stock.'],title:['库存与补货复盘','STOCK / REPLENISHMENT REVIEW'],
  source:['库存记录 / 可用、在途与缺货','STOCK / AVAILABLE, INCOMING AND GAPS'],
  plan:['结合需求和交期，安排补货。','Plan replenishment around demand and lead time.'],
  actual:['一起核对缺货记录与库存积压。','Check stockouts alongside excess inventory.'],
  action:['先区分原因，再调整补货量和节奏。','Find the cause; adjust reorder quantity and timing.']},
 {id:'margin',report:5,text:['利润，要看完整成本。','Margin depends on the full cost.'],title:['成本与利润复盘','COST / MARGIN REVIEW'],
  source:['成本记录 / 报价与实际费用','COST / QUOTE AND ACTUAL EXPENSES'],
  plan:['保留提案报价与目标售价。','Retain the proposal quote and target price.'],
  actual:['核对材料、加工、包装和运输。','Review materials, labour, packaging and freight.'],
  action:['补全成本，再复核定价与产品结构。','Review pricing and design against the full cost.']},
 {id:'delivery',report:5,text:['承诺的交期，实际做到了吗？','Did delivery meet the promise?'],title:['订单与履约复盘','ORDER / DELIVERY REVIEW'],
  source:['订单记录 / 承诺与实际交付','ORDERS / PROMISED AND ACTUAL DELIVERY'],
  plan:['保留确认数量、规格与交期。','Keep the agreed quantity, specs and due date.'],
  actual:['对照生产、出货与签收记录。','Compare production, dispatch and receipt.'],
  action:['找到延误环节，修正下一轮交付安排。','Locate delays; improve the next delivery plan.']},
 {id:'quality',report:5,text:['交付中的问题，也要留下来。','Keep the lessons from delivery.'],title:['质量与工作复盘','QUALITY / PROCESS REVIEW'],
  source:['质量记录 / 验收与问题处理','QUALITY / ACCEPTANCE AND RESOLUTION'],
  plan:['明确样品与交付验收要求。','Define sample and delivery acceptance criteria.'],
  actual:['关联检查记录、退换与处理结果。','Link inspections, returns and resolutions.'],
  action:['把问题带回规格、说明和验收要求。','Feed lessons into specs, instructions and checks.']},
];
