// Public product observations are separated from authored concepts and illustrative reviews.
// Source notes and retrieval date: docs/智能展厅内容依据.md. No market-size or sales claims.
export const proposalDirections = [
 {id:'lip',title:['润色唇油','Tinted lip oil'],subtitle:['一抹透色，随身补妆','A sheer wash, on the go'],tag:['涂抹体验','APPLICATION'],facts:[['凝胶转油质地','Gel-to-oil texture'],['斜面刷头控制用量','Angled applicator'],['需验证残留与黏感','Test residue and tack']],source:'Rare Beauty',accent:'#d3a6a9'},
 {id:'cheek',title:['轻雾腮红','Soft veil blush'],subtitle:['少量叠加，柔化边缘','Layer lightly. Diffuse the edge.'],tag:['上色方式','COLOUR BUILD'],facts:[['凝胶乳霜形态','Gel-cream format'],['指腹晕染与叠色','Finger blend and layer'],['需验证不同底妆兼容性','Test base compatibility']],source:'Glossier',accent:'#d9a395'},
 {id:'tint',title:['轻透底妆','Sheer skin tint'],subtitle:['保留肌肤自身的质感','Let skin texture show'],tag:['覆盖与肤感','COVERAGE / FEEL'],facts:[['轻薄覆盖方向','Sheer coverage direction'],['光泽与色调匹配','Finish and shade match'],['需验证分层与取用','Test settling and dispensing']],source:'ILIA',accent:'#c8b396'},
 {id:'light',title:['柔光高光棒','Soft light stick'],subtitle:['在需要的位置，添一束光','Place light with precision'],tag:['局部提亮','PLACEMENT'],facts:[['膏转粉质地参照','Cream-to-powder reference'],['颧骨与眉骨局部使用','Target cheek and brow bones'],['需验证推开后的边界','Test blend-out edges']],source:'Fenty Beauty',accent:'#d7cdb4'},
 {id:'palette',title:['柔雾四色眼影','Soft Haze palette'],subtitle:['打底、过渡、加深、提亮','Base. Blend. Define. Illuminate.'],tag:['配色与结构','COLOUR / CONSTRUCTION'],facts:[['四种用途，一盘完成','Four roles in one compact'],['雾面与缎光搭配','Matte with satin accents'],['镜面盒盖与便携结构','Mirror lid, portable case']],source:null,accent:'#cdb7a4'},
];
export const researchReports = [
 {title:['使用反馈笔记','Use-experience notes'],kind:['演示评价 · 定性整理','ILLUSTRATIVE REVIEWS'],lines:[['“配色很好看，但不知道先用哪格。”','“Lovely shades. Which one goes first?”'],['“出门只想带一盘和一面镜子。”','“One palette and a mirror for travel.”'],['归纳：用途标识与便携收纳','Brief: shade roles and portability']],question:['待验证：新手能否独立完成搭配？','Test: can a beginner build a look?']},
 {title:['品类形态对照','Format comparison'],kind:['公开商品规格 · 横向观察','PUBLIC PRODUCT FORMATS'],lines:[['唇油：刷头取用与叠涂','Lip oil: applicator and layering'],['腮红：凝胶乳霜与晕染','Blush: gel-cream and diffusion'],['底妆：轻薄覆盖与色调匹配','Tint: sheer coverage and shade match']],question:['规格参照，不代表市场份额或趋势','Product observations, not market share']},
 {title:['质地与妆效研究','Texture / finish study'],kind:['品牌产品说明 · 设计参照','PUBLISHED FINISH DESCRIPTIONS'],lines:[['凝胶转油：光泽与留色','Gel to oil: gloss and tint'],['膏转粉：涂抹与柔化边缘','Cream to powder: glide and blend'],['设计映射：雾面打底，缎光提亮','Design: matte base, satin highlight']],question:['待验证：飞粉、黏感与叠涂均匀度','Test: fallout, tack and even layering']},
 {title:['四色功能分工','Four-shade architecture'],kind:['原创配色提案 · 待打样','AUTHORED COLOUR PROPOSAL'],lines:[['象牙白打底 / 玫瑰色过渡','Ivory base / rose transition'],['灰褐色加深 / 香槟色提亮','Taupe definition / champagne light'],['按用途组合，避免相近色重复','Organize by role, avoid redundant shades']],question:['待验证：不同肤色下的显色关系','Test: colour payoff across skin tones']},
 {title:['随行结构要求','Portable construction'],kind:['原创产品要求 · 待打样','AUTHORED PRODUCT REQUIREMENTS'],lines:[['盒盖内置镜面，减少额外携带','Mirror in the lid, one less item to carry'],['四个独立色盘，留出取粉空间','Four separate pans with brush clearance'],['铰链、扣合与盒壁共同成形','Hinge, clasp and case built together']],question:['待验证：开合寿命与运输保护','Test: hinge cycles and transit protection']},
 {title:['样品评审清单','Sample review checklist'],kind:['验证计划 · 尚无实测结论','VALIDATION PLAN / NO TEST RESULTS'],lines:[['看：实际肤色下的显色与层次','See: payoff and contrast on skin'],['用：取粉、晕染与卸除体验','Use: pickup, blending and removal'],['带：盒盖、镜面与扣合稳定性','Carry: lid, mirror and clasp stability']],question:['形成样品后，再记录实测结果','Record results after samples exist']},
];
export const informationFragments = [
 ['Review · easy to blend','评价 · 容易晕染'],['Review · shades work together','评价 · 配色好搭'],['Review · mirror for travel','评价 · 出门要镜子'],['Review · less to carry','评价 · 少带几件'],['Review · soft to the touch','评价 · 触感柔和'],['Review · where do I start?','评价 · 先用哪格？'],
 ['Format · lip oil','规格 · 润色唇油'],['Format · gel-cream blush','规格 · 凝胶腮红'],['Format · skin tint','规格 · 轻透底妆'],['Format · highlight stick','规格 · 高光棒'],['Format · compact palette','规格 · 便携眼影盘'],['Source · product descriptions','来源 · 商品说明'],
 ['Finish · gel to oil','质地 · 凝胶转油'],['Finish · cream to powder','质地 · 膏转粉'],['Application · buildable colour','涂抹 · 逐层叠色'],['Application · angled wand','涂抹 · 斜面刷头'],['Finish · satin accent','妆效 · 缎光提亮'],['Question · even blending?','问题 · 晕染均匀？'],
 ['Ivory · base','象牙白 · 打底'],['Rose · transition','玫瑰色 · 过渡'],['Taupe · definition','灰褐色 · 加深'],['Champagne · light','香槟色 · 提亮'],['Design · four colour roles','设计 · 四色分工'],['Test · skin-tone range','验证 · 不同肤色'],
 ['Structure · mirror lid','结构 · 镜面盒盖'],['Structure · four pans','结构 · 四格色盘'],['Structure · brush clearance','结构 · 取粉空间'],['Structure · hinge','结构 · 铰链'],['Structure · clasp','结构 · 扣合'],['Use · travel case','场景 · 随行收纳'],
 ['Test · powder fallout','验证 · 飞粉'],['Test · blend-out edge','验证 · 晕染边界'],['Test · colour payoff','验证 · 显色'],['Test · opening cycles','验证 · 开合寿命'],['Test · mirror protection','验证 · 镜面保护'],['Test · transit stability','验证 · 运输稳定性'],
];
