// A review is one source in a wider business feedback loop. These are illustrative
// record structures and review questions, never asserted operating results.
export const feedbackSources = [
 {id:'customer',report:0,text:['很棒的产品。','Great product.'],title:['客户使用反馈','CUSTOMER FEEDBACK'],
  source:['使用体验 / 演示摘录','USE EXPERIENCE / DEMO']},
 {id:'sales',report:3,text:['预测销量与实际销售差异','Forecast versus actual sales'],title:['销售与预测复盘','SALES / FORECAST REVIEW'],
  source:['销售记录 / 商品、期间与渠道','SALES / PRODUCT, PERIOD AND CHANNEL'],
  plan:['预测销量、预计销售额与预测版本。','Forecast units, revenue and forecast version.'],
  actual:['同期实销数量、销售金额与退货记录。','Actual units, revenue and returns for the same period.'],
  action:['归因销售偏差，修订下一周期需求预测。','Analyse sales variance; revise the next demand forecast.']},
 {id:'inventory',report:3,text:['缺货影响与库存周转分析','Stockout impact and inventory turnover'],title:['库存与补货复盘','STOCK / REPLENISHMENT REVIEW'],
  source:['库存记录 / 可用、在途与缺货','STOCK / AVAILABLE, INCOMING AND GAPS'],
  plan:['需求预测、补货数量与计划到货日期。','Demand forecast, reorder quantity and planned arrival.'],
  actual:['可用库存、缺货天数、库龄与在途数量。','Available stock, stockout days, stock age and incoming units.'],
  action:['区分供货约束与需求不足，调整补货批量及频次。','Separate supply constraints from weak demand; adjust replenishment.']},
 {id:'margin',report:5,text:['分项成本归集与产品利润测算','Itemised costs and product margin'],title:['成本与利润复盘','COST / MARGIN REVIEW'],
  source:['成本记录 / 报价与实际费用','COST / QUOTE AND ACTUAL EXPENSES'],
  plan:['分项报价、目标售价与利润测算口径。','Itemised quote, target price and margin assumptions.'],
  actual:['材料、加工、包装及运输实际费用。','Actual material, processing, packaging and freight costs.'],
  action:['统一成本口径，复核报价偏差与产品利润。','Reconcile cost definitions; review quote variance and margin.']},
 {id:'delivery',report:5,text:['计划交期与实际交付节点对照','Planned and actual delivery milestones'],title:['订单与履约复盘','ORDER / DELIVERY REVIEW'],
  source:['订单记录 / 约定交期与履约节点','ORDERS / DUE DATE AND DELIVERY MILESTONES'],
  plan:['订单数量、确认规格与约定交付日期。','Order quantity, approved specifications and agreed due date.'],
  actual:['完工、出货、签收日期与实交数量。','Completion, dispatch, receipt dates and delivered quantity.'],
  action:['定位履约偏差，修订排产与交付计划。','Identify delivery variance; revise production and delivery plans.']},
 {id:'quality',report:5,text:['质量验收与整改结果追溯','Quality inspection and corrective actions'],title:['质量与工作复盘','QUALITY / PROCESS REVIEW'],
  source:['质量记录 / 验收与问题处理','QUALITY / ACCEPTANCE AND RESOLUTION'],
  plan:['确认样品、检验项目与验收标准。','Approved sample, inspection items and acceptance criteria.'],
  actual:['检验结果、退换原因与整改复核记录。','Inspection results, return reasons and corrective-action checks.'],
  action:['追溯问题原因，更新产品规格与检验要求。','Trace root causes; update specifications and inspection criteria.']},
];
