import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, ArrowUpRight, MagnifyingGlass, X } from '@phosphor-icons/react';
import { Modal } from './Dialogs';

const matches = (record, q) => !!record && `${record.id} ${record.name} ${record.label?.join(' ') || ''}`.toLowerCase().includes(q.trim().toLowerCase());
export const brandMatch = (record, featured) => featured.find(b => b.name.toLowerCase().replace(/[^a-z0-9]/g,'') === record?.name.toLowerCase().replace(/[^a-z0-9]/g,''));

export function CatalogBrowser({ type, catalog, featured, lang, onClose, onBrand, remembered, onRemember }) {
  const l=lang==='zh'?0:1, t=(zh,en)=>l===0?zh:en, isBrand=type==='brands';
  const [query,setQuery]=useState(remembered?.query || ''), [group,setGroup]=useState(remembered?.group || 'all'), [page,setPage]=useState(remembered?.page || 0);
  const [selected,setSelected]=useState(remembered?.selected || (isBrand?catalog.brands[0].id:catalog.categories[0].id)),[detail,setDetail]=useState(null);
  const records=isBrand?catalog.brands:catalog.categories;
  const rows=useMemo(()=>records.filter(r=>(matches(r,query)||(!isBrand&&catalog.subcategories.some(s=>s.parent===r.id&&matches(s,query))))&&(!isBrand||group==='all'||(group==='other'?!/^[a-z]/i.test(r.name):new RegExp(`^[${group}]`,'i').test(r.name)))).sort((a,b)=>isBrand?a.name.localeCompare(b.name):a.id.localeCompare(b.id)),[records,query,group,isBrand,catalog]);
  const pages=Math.max(1,Math.ceil(rows.length/12)), currentPage=Math.min(page,pages-1), shown=rows.slice(currentPage*12,(currentPage+1)*12);
  const record=records.find(r=>r.id===selected), brand=isBrand?brandMatch(record,featured):null;
  useEffect(()=>{if(rows.length&&!rows.some(r=>r.id===selected))setSelected(rows[0].id);},[query,group]);
  const children=!isBrand?catalog.subcategories.filter(c=>c.parent===selected&&(!query||matches(record,query)||matches(c,query))):[];
  const remember=()=>onRemember({selected,query,group,page:currentPage});
  const select=id=>{setSelected(id);setDetail(null);};
  return <Modal title={t(isBrand?'品牌档案':'品类总览',isBrand?'Brand archive':'Category index')} onClose={()=>{remember();onClose();}} className="catalog-browser">
    <div className="catalog-main"><header className="catalog-header"><p className="eyebrow">PARAMONT / {isBrand?'BRAND ARCHIVE':'CATEGORY INDEX'}</p><h2>{t(isBrand?'每一种个性，都值得被看见。':'从品类，发现更多可能。',isBrand?'Every identity deserves a space.':'A world of possibilities.')}</h2><p>{isBrand?t(`${catalog.brands.length} 条品牌档案`,`${catalog.brands.length} archive records`):t(`${catalog.categories.length} 大类 · ${catalog.subcategories.length} 细分类`,`${catalog.categories.length} categories · ${catalog.subcategories.length} subcategories`)}</p></header>
      <div className="catalog-tools"><label className="catalog-search"><MagnifyingGlass size={23}/><input value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}} placeholder={t(isBrand?'搜索名称或编码':'搜索品类、细分类或编码',isBrand?'Search name or code':'Search categories, subcategories or codes')} aria-label={t('搜索档案','Search archive')}/>{query&&<button onClick={()=>{setQuery('');setPage(0);}} aria-label={t('清空搜索','Clear search')}><X size={20}/></button>}</label>
      {isBrand&&<div className="alphabet-filter">{[['all',t('全部','All')],['a-f','A–F'],['g-l','G–L'],['m-r','M–R'],['s-z','S–Z'],['other','#']].map(([id,label])=><button key={id} className={group===id?'active':''} aria-pressed={group===id} onClick={()=>{setGroup(id);setPage(0);}}>{label}</button>)}</div>}</div>
      <div className="archive-grid">{shown.map(r=><button key={r.id} onClick={()=>select(r.id)} aria-pressed={selected===r.id} className={selected===r.id?'selected':''}><small>{isBrand?(r.undefined?t('未定义记录','UNDEFINED RECORD'):r.name.slice(0,1).toUpperCase()):r.id}</small><span>{!isBrand?r.label[l]:r.name}</span>{!isBrand&&<em>{r.name}</em>}<ArrowUpRight size={20}/></button>)}{!shown.length&&<div className="catalog-empty"><MagnifyingGlass size={35}/><h3>{t('没有匹配的档案','No matching records')}</h3><button className="text-button" onClick={()=>{setQuery('');setGroup('all');setPage(0);}}>{t('清空筛选，查看全部','Clear filters and view all')}<ArrowRight/></button></div>}</div>
      <footer className="catalog-pagination"><span>{t(`找到 ${rows.length} 条`,`${rows.length} records`)}</span><div><button className="icon-button" disabled={currentPage===0} onClick={()=>setPage(p=>p-1)} aria-label={t('上一页档案','Previous archive page')}><ArrowLeft/></button><span>{String(currentPage+1).padStart(2,'0')} / {String(pages).padStart(2,'0')}</span><button className="icon-button" disabled={currentPage===pages-1} onClick={()=>setPage(p=>p+1)} aria-label={t('下一页档案','Next archive page')}><ArrowRight/></button></div></footer>
    </div>
    <aside className="archive-detail" key={selected}>{rows.length ? <>
      <div className="archive-identity"><span className="archive-watermark">{isBrand?(record?.name.slice(0,1)||'P'):record?.id}</span><p className="eyebrow">{t(isBrand?'档案聚焦':'品类聚焦',isBrand?'IN FOCUS':'CATEGORY IN FOCUS')}</p>{brand?<img className="archive-logo" src={`/media/brand/${brand.logo}`} alt={brand.name}/>:<h3>{isBrand?record?.name:record?.label[l]}</h3>}<span className="archive-code">{record?.id}</span></div>
      <div className="archive-description">{isBrand?<><h3>{brand?brand.descriptor[l]:t('品牌档案','Brand record')}</h3><p>{brand?brand.description[l]:t(record?.undefined?'原表中的未定义记录，暂不进入品牌展示。':'已收录名称与编码。品牌介绍、标志和产品资料待补充。',record?.undefined?'An undefined record from the source archive.':'Name and code are available. Brand story, logo and product details are awaiting content.')}</p><dl><div><dt>{t('资料来源','Source')}</dt><dd>{t('公司品牌档案','Company archive')}</dd></div><div><dt>{t('品类关系','Category relationship')}</dt><dd>{t('待补充','To be added')}</dd></div></dl>{brand&&<button className="pill-button" onClick={()=>{remember();onBrand(brand);}}>{t('探索品牌与概念样品','Explore brand & concept studies')}<ArrowUpRight size={23}/></button>}<p className="archive-footnote">{t('档案收录不代表品牌归属。','Archive inclusion does not indicate brand ownership.')}</p></>:<><div className="subcategory-heading"><h3>{t('细分类','Subcategories')}</h3><span>{children.length}</span></div><div className="subcategory-list">{children.map(c=><button key={c.id} className={detail===c.id?'active':''} aria-pressed={detail===c.id} onClick={()=>setDetail(detail===c.id?null:c.id)}><span><small>{c.id}</small>{c.name}</span><ArrowUpRight size={18}/>{detail===c.id&&<p>{t('产品图集与样品资料待补充。','Product gallery and sample details are awaiting content.')}</p>}</button>)}</div><p className="archive-footnote">{t('点击细分类展开产品资料。','Select a subcategory to expand its product information.')}</p></>}</div>
    </> : <div className="archive-none"><MagnifyingGlass size={40}/><h3>{t('换个词，再发现。','Try another search.')}</h3><p>{t('可尝试名称、编码，或清空筛选。','Try a name or code, or clear the filters.')}</p></div>}</aside>
  </Modal>;
}
