// Display translations only. Preserve source names and identifiers for provenance.
const entries=`
Bunting Pennants=三角串旗
Cozy Craftworks=Cozy Craftworks
Kitchenware=厨具
Adult Impulse=成人趣味小物
Kids Impulse=儿童趣味小物
Pet=宠物用品
Compound - Foam Clay=泡沫黏土材料
Foam Clay=泡沫黏土
Education=益智教育
Cosmetic Kit=美妆套装
Lint Roller=粘毛滚筒
Candle Making=蜡烛制作
Bath Salt=浴盐
Stickers - Alphabet=字母贴纸
On The Go Accessories=随行配件
Wearables=穿戴饰品
Drinkware=饮水器具
Baking Pan-Mold=烘焙盘与模具
Office Tools=办公工具
Nail Sets=美甲套装
Hair Accessory Set=发饰套装
Stickers - Scrapbooking=剪贴簿贴纸
Papercraft-Scrapbooking=纸艺与剪贴簿
Fill=填充材料
Charms=装饰挂件
Skincare=护肤用品
Pencil Sharpener=卷笔刀
Lip Mask=唇膜
Hair Tools=美发工具
Eye Care=眼部护理
Tote Bag=手提袋
Baby=婴幼儿用品
Wristband=腕带
Bubble Bath=泡泡浴
Puzzles=拼图
Tape - Craft=手工胶带
Tools=工具
Stickers - Vinyl=乙烯基贴纸
Stickers - Gems=宝石贴纸
Stickers - Felt=毛毡贴纸
Keychains=钥匙扣
Bookmarks=书签
Classroom Tools=教室用具
Classroom Decor=教室装饰
Kind Mind=Kind Mind
Gemstones=装饰宝石
Hair Claw=抓夹
Baking Bag=裱花袋
Baking tips=裱花嘴
Craft-plastic=塑料手工材料
Tooblerz=Tooblerz
CleanColoring Markers=CleanColoring 洁净涂色笔
CleanColoring Paint=CleanColoring 洁净涂色颜料
Coloring Books=涂色本
Crayons=蜡笔
Magic Marker=魔法彩笔
Markers=马克笔
Paint=颜料
Paint Brushes=画笔
Paint Marker=丙烯马克笔
Paint Pallets=调色盘
Paints & Paint Activity=颜料与绘画活动
Scratch Art=刮画
Sponges - Paint Rollers=海绵滚筒画刷
Sponges - Art=美术海绵
Watercolor Set=水彩套装
Balloons=气球
Bath Bomb=沐浴泡腾球
Mittens & Gloves=手套
Blemish Tool Kit=瑕疵护理工具套装
Brush=刷具
Cosmetic Brushes=化妆刷
Cosmetic Finger Blender=指套美妆海绵
Eye Shadow=眼影
Eyebrow Shaper=修眉工具
Eyelash Curler=睫毛夹
Eyelashes=假睫毛
Face Mask=面部敷膜
Facial Brush=洁面刷
Facial Buff=面部清洁棉
Facial Mask=面膜
Facial Roller=面部滚轮
Facial Shaver=面部修毛器
Lip Color=唇部彩妆
Lip Glitter=唇部亮粉
Lip Gloss=唇彩
Lip Plumper=丰唇产品
Lip Repair=唇部修护
Lip Scrub=唇部磨砂
Lip Stick=口红
Makeup Kit=彩妆套装
Mirror=镜子
Nylon Bags=尼龙包袋
Skin Care Tool=护肤工具
Sponges - Cosmetic=美妆海绵
Tweezers=镊子
3D Kit=立体手工套装
3D Printing=三维打印
Beads=串珠
Beads - Pearls=仿珍珠串珠
Beads - Pony Beads=大孔彩珠
Bells=铃铛
Canvas Art=画布美术
Cast Iron Alphabet=铸铁字母装饰
Chalk=粉笔
Chalkboard - Tags=黑板标签
Chenille Stems=扭扭棒
Clothespins=衣夹
Composition Book=作文本
Compounds - Air Dry Clay=风干黏土
Compounds - Clay=黏土
Compounds - Cloud Sand=云朵沙
Compounds - Dough=彩泥
Compounds - Kits & Sets=造型材料套装
Compounds - Putty=弹力泥
Compounds - Sand=玩具沙
Compounds - Slime=史莱姆
Compounds - Snough Ball=Snough Ball 造型材料
Cording - Elastic=弹力绳
Cording - Elastic Bands=橡皮筋
Cording - Jute=黄麻绳
Cording - Twine=手工细绳
Craft Kits=手工套装
Craft Sticks=手工棒
Craft Value=手工材料组合装
Cross Stitch=十字绣
Embroidered Patches=刺绣布贴
Embroidery Thread=绣线
Faux Snow=仿真雪
Feathers=羽毛
Felt Sheets=毛毡片
Flexible Magnets=软磁材料
Foam - 3D Kit=泡棉立体手工套装
Foam - Craft=泡棉手工材料
Foam - Shapes=泡棉形状片
Foam - Sheets=泡棉片
Fur=绒毛材料
Glitter=闪粉
Glitter Glue=闪粉胶
Glue=胶水
Hand Kit=手作套装
Jewelry - Shrink=热缩饰品
Jewelry - Wood Jewelry Kit=木质饰品套装
Lolly Stick Kit=冰棒棍手工套装
Mason Jar Crafts=梅森罐手工
Needle Craft=针线手工
Polyfoam - Shape=泡沫塑料造型
Pom Pom Trim=毛球花边
Pom Poms=毛球
Rainbow Heart Kit=彩虹爱心套装
Ribbon=丝带
Rock Paint Kit=石头彩绘套装
Sand Art=沙画
Scissors=剪刀
Sequins=亮片
Sewing Kit=缝纫套装
Sign=标牌
Stickers - Chipboard=厚纸板贴饰
Stickers - EVA=EVA 泡棉贴纸
Storage Box=收纳盒
Suncatchers=透光挂饰
Tape - Foam=泡棉胶带
Tape - Glitter=闪粉胶带
Tattoo Pen=纹身笔
Wiggle Eyes=活动眼睛配件
Wood - Clothes Pins=木衣夹
Wood - Craft=木质手工材料
Wood - Sticks=木棒
Yarn Craft Kit=毛线手工套装
Hair Bands=发箍
Hair Clips & Decoration=发夹与发饰
Hair Color=染发用品
Hair Ties=发绳
Hairpins=发卡
Headband=头带
Scissor & Comb Set=剪刀梳子套装
Scrunchie=布艺发圈
Travel Bag & Bottles=旅行袋与分装瓶
Travel Bottle=旅行分装瓶
Travel/Sport Bag=旅行运动包
Candle - Décor=装饰蜡烛
Door Cover=门饰
Figurine=摆件
Flower Pot=花盆
Frame - Wood=木相框
Garden Flag=庭院旗
Gel Clings=凝胶窗贴
Vase=花瓶
Wood - Décor=木质装饰
Doilies=花边纸垫
Egg Whisk=打蛋器
Jewelry=饰品
Jewelry - Bracelets=手链
Jewelry - Necklace=项链
Jewelry - Novelty=趣味饰品
Jewelry -Slap Bracelets & Other Metal Jewelry=啪啪圈与金属饰品
Callus Remover=去茧工具
Clipper & Tweezer Set=指甲剪镊子套装
Cuticle Oil=指缘护理油
Cuticle Trimmer=死皮修剪器
Emery Board=砂条
Manicure Set=手部美甲套装
Nail Block=美甲磨块
Nail Brush=指甲刷
Nail Buffer=指甲抛光块
Nail Clipper=指甲剪
Nail Essentials=基础美甲工具
Nail File=指甲锉
Nail Nipper Set=指甲钳套装
Nail Pen=美甲笔
Nail Polish=指甲油
Nail Smoother=指甲打磨器
Nail Soak Off Clips=卸甲夹
Nail Wrap=美甲贴膜
Nail Wraps=美甲贴膜
Nails - Press on Nails=穿戴甲
Pedicure Paddle=足部磨板
Pedicure Set=足部护理套装
Pumice Stone=磨脚石
Clip Organizer=夹具收纳
Metal Paper Clips=金属回形针
Paper Clips=回形针
Paper Clips - Other=其他回形针
Push Pins=图钉
Sequin Bag=亮片包
Tape=胶带
Thumb Tacks=平头图钉
Bubbles=泡泡玩具
Cake Topper=蛋糕插牌
Candle - Party=派对蜡烛
Confetti=彩纸屑
Confetti Heart=爱心彩纸屑
Cupcake Liners/Wraps=纸杯蛋糕托与围边
Face Paint=面部彩绘
Felt Banner=毛毡旗帜
Fetti Pop=Fetti Pop
Give-Aways=派对赠品
Masks=面具
Mini Dinosaurs=迷你恐龙
Mini Maracas=迷你沙锤
Mini Nutcracker=迷你胡桃夹子
Mini Spidey Balls=迷你蜘蛛球
Mini Stampers=迷你印章
Novelty Glasses=趣味眼镜
Paper Bags & Boxes=纸袋与纸盒
Paper Napkins=餐巾纸
Paper Tableware=纸餐具
Party Decor/Favors=派对装饰与礼品
Plastic Cup, Plates Bowls=塑料杯盘碗
Plastic Kitchenware=塑料厨具
Plastic Table Cover=塑料桌布
Play Money=玩具钱币
Pullback Car=回力车
Silly Streamers=派对喷丝
Table Scatter=桌面撒饰
Tablecloth=桌布
Treasure Coins=宝藏金币玩具
Whistles=口哨
Wood - Food Picks=木质食物签
Eggs & Marker=彩蛋与画笔
Mail Box=信箱
Mini Trees=迷你树饰
Snowglobe=雪花水晶球
Bag Décor=包袋装饰
Ornament Hooks=挂饰钩
Ornaments=装饰挂件
Tinsel=彩条装饰
Wood - Statues / Ornaments=木质雕像与挂饰
Wreath=花环
Bags=包袋
Cases / Satchels=箱包与挎包
Felt Basket=毛毡篮
Felt Easter Basket=毛毡复活节篮
Foam Basket=泡棉篮
Plastic Heart=塑料爱心
Binders / Folders=活页夹与文件夹
Cards & Envelopes=卡片与信封
Erasers=橡皮擦
Highlighters=荧光笔
Journal=手账本
List Pad=清单便笺
Notebooks=笔记本
Notepads=便笺本
Pencil Case=笔袋
Pencils=铅笔
Pencils - Mechanical Pencils=自动铅笔
Pens=书写笔
Pens - Ballpoint=圆珠笔
Pens - Felt Tip=纤维笔
Pens - Gel Pen=中性笔
Pens - Mini=迷你笔
Pens - Mini Gel Pens=迷你中性笔
Pens - Rainbow Pens=彩虹笔
Planner=计划本
Stamper=印章
Stationery Kit=文具套装
Stationery Pouch=文具收纳袋
Stencils=绘画模板
Stickers=贴纸
To-Do List=待办清单
Bobbler=摇摆玩具
Pens - Squishable Pen=可捏软胶笔
Flying Ball=飞行球
Frog Jumpers=弹跳青蛙
Games=游戏
Magic Wands=魔法棒
Rocket Launcher=火箭发射玩具
Sand Tools=玩沙工具
Soccer Accessories=足球配件
Squishy=慢回弹玩具
Tin Game=铁盒游戏
Toy Kit=玩具套装
Water Gun=水枪
Whackable=拍打玩具
Wood - Toy=木质玩具
Nail Sticker=美甲贴纸
Ceramics=陶瓷
Paper Wrappings=包装纸
Clothes Pins - Plastic=塑料衣夹
Clothes Pins - Wood=木衣夹
Bath Toy - EVA=EVA 泡棉洗澡玩具
Bath Toy - Plastic=塑料洗澡玩具
Loofah=沐浴丝瓜络
STEM Kit=科学探索套装
Card&Board Games=卡牌与桌面游戏
Indoor & Outdoor Play=室内外玩乐
`;
export const categoryChinese=Object.fromEntries(entries.trim().split('\n').map(line=>{const index=line.indexOf('=');return [line.slice(0,index),line.slice(index+1)];}));
export function withCatalogLabels(catalog){return {...catalog,subcategories:catalog.subcategories.map(row=>({...row,label:row.label||[categoryChinese[row.name]||row.name,row.name]}))};}
